export const lang = {
  cancel: "Cancel",
  confirm: "Confirm",
  create: "Create",
  createSticker: "Create Sticker",
  delete: "Delete",
  doYouConfirmDeleteSticker: "Do you confirm to delete sticker?",
  doYouConfirmDiscardChanges: "Do you confirm to discard changes?",
  editSticker: "Edit Sticker",
  enterTextForSticker: "Enter text for sticker...",
  error404: "Oops... the page wasn't found!",
  somethingWentWrong: "Something went wrong...",
  thereIsNoStickersYet: "There is no stickers yet...",
  thereIsNoStickersYetLetsAdd: [
    "There is no stickers yet...",
    "Let's add first one!",
  ],
  thisActionCannotBeUndone: "This action cannot be undone.",
  update: "Update",
};
